// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtSyhT_eubb39a6mlZc_laIM5Y3Ov8ltM',
    appId: '1:129189890654:web:09b5ec8b46f950468182cf',
    messagingSenderId: '129189890654',
    projectId: 'vodafone-follow-up',
    authDomain: 'vodafone-follow-up.firebaseapp.com',
    storageBucket: 'vodafone-follow-up.appspot.com',
    measurementId: 'G-VCTPEQB2J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXV-TPuNzy0_wURezS0AWnp8YNuW-IXD8',
    appId: '1:129189890654:android:76748e6f2ccfa6a58182cf',
    messagingSenderId: '129189890654',
    projectId: 'vodafone-follow-up',
    storageBucket: 'vodafone-follow-up.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0XMCY9pz2LVuOMjI78qJK_2YojCEcAKg',
    appId: '1:129189890654:ios:6bc27e536eab571e8182cf',
    messagingSenderId: '129189890654',
    projectId: 'vodafone-follow-up',
    storageBucket: 'vodafone-follow-up.appspot.com',
    iosClientId: '129189890654-c24ufha4e94as6o3fasqv3tutv8j0q3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.vodafoneFollowup',
  );
}
